[workspace]
members = [
  "exercises/01_basics/00_welcome",
  "exercises/01_basics/01_setup",
  "exercises/01_basics/02_functions",
  "exercises/01_basics/03_components",
  "exercises/01_basics/04_components_contd",
  "exercises/02_http/00_spin",
  "exercises/02_http/00_spin/tests",
  "exercises/02_http/01_requests",
  "exercises/02_http/01_requests/tests",
  "exercises/02_http/02_handler",
  "exercises/02_http/02_handler/tests",
  "verifier",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.48", features = ["derive"] }
spin-test-sdk = { git = "https://github.com/spinframework/spin-test", version = "0.1.0" }
wasmtime = "37.0.1"
wasmtime-wasi = "37.0.1"
