spin_manifest_version = 2

[application]
name = "requests"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "requests"

[component.requests]
source = "../../../target/wasm32-wasip1/debug/requests.wasm"
allowed_outbound_hosts = ["http://www.randomnumberapi.com"]
[component.requests.build]
command = "cargo build -p requests --target wasm32-wasip1"

[component.requests.tool.spin-test]
source = "../../../target/wasm32-wasip1/debug/requests_tests.wasm"
