[target.wasm32-unknown-unknown]
runner = "cargo run --package verifier --bin verifier -- wasmtime-module "

[target.wasm32-wasip2]
runner = "cargo run --package verifier --bin verifier -- wasmtime-component "
