[package]
name = "databases"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
fallible-iterator.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-querystring.workspace = true
serde_json.workspace = true
spin-sdk.workspace = true
