[[verification]]
command = "cargo"
args = ["build", "-p", "key_value_tests", "--target", "wasm32-wasip1"]

[[verification]]
command = "spin"
args = ["build"]

[[verification]]
command = "spin"
args = ["test"]
