spin_manifest_version = 2

[application]
name = "routing"
version = "1.0.0"

[[trigger.http]]
route = "/eval"
component = "databases"

[[trigger.http]]
route = "/clear/..."
component = "routing"

[component.databases]
source = "../../../target/wasm32-wasip1/debug/databases.wasm"
sqlite_databases = ["default"]

[component.databases.build]
command = "cargo build -p databases --target wasm32-wasip1"
watch = ["../04_databases/src/**/*.rs", "Cargo.toml"]

[component.routing]
source = "../../../target/wasm32-wasip1/debug/routing.wasm"
sqlite_databases = ["default"]

[component.routing.build]
command = "cargo build -p routing --target wasm32-wasip1"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.routing.tool.spin-test]
source = "../../../target/wasm32-wasip1/debug/routing_tests.wasm"
