spin_manifest_version = 2

[application]
name = "spin-http-random"
version = "1.0.0"

[[trigger.http]]
route = "/eval/"
component = "spin-http-eval-assign"

[[trigger.http]]
route = "/clear/..."
component = "spin-http-eval-clear"

[component.spin-http-eval-assign]
source = "../../../target/wasm32-wasip1/release/spin_http_eval_assign.wasm"
key_value_stores = ["default"]
[component.spin-http-eval-assign.build]
command = "cargo build -p spin-http-eval-assign --target wasm32-wasip1 --release"

[component.spin-http-eval-clear]
source = "../../../target/wasm32-wasip1/release/spin_http_eval_assign_clear.wasm"
key_value_stores = ["default"]
[component.spin-http-eval-clear.build]
command = "cargo build -p spin-http-eval-assign-clear --target wasm32-wasip1 --release"
