name: "Site"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # First day of a month
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install plugin
        run: cargo install --git https://github.com/mainmatter/100-exercises-to-learn-rust mdbook-exercise-linker
      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - name: Build book
        run: |
          cd book
          mdbook build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: |
            --exclude-loopback
            --require-https
            --no-progress
            book/book
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: "book/book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
